#import "String";
#import "Basic";
#import "Sort";
#import "Bit_Operations";
#import "Compiler";

#load "world.jai"; // Everything lives here
#load "archetype.jai"; // Everything stores here
#load "signature.jai"; // Everything can be described by a couple digits
#load "system.jai"; // Everything can do
#load "entity.jai"; // Everything know it's place
#load "query.jai"; // Everything can be found